version: '2.4' # Needed for resource allocation
services:

  windows-container-but-useful:
    build: ./windows-container-but-useful/main
    image: "windows-container-but-useful"
    mem_limit: 8192m
    cpu_count: 4
    container_name: windows-container-but-useful
    restart: unless-stopped
    stdin_open: true
    ports:
      - "1222:22/tcp" #Expose SSH to a non-standard port
      - "55985":5985/tcp" #PSRemoting HTTP Port
      - "55986:5986/tcp" #PSRemoting HTTPS Port
